name: Deploy to EC2

on:
  push:
    branches:
      - main  # Se activa cada vez que subes algo a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar comandos remotos por SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /srv/apache-cicd
            # Si la carpeta está vacía, clonamos. Si no, actualizamos.
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git pull origin main
            fi
            # Levantamos el contenedor con los cambios nuevos
            docker compose up -d --build
